name: test
title: "[test value and default]: "
description: test
labels: ["lables"]
body:
  - type: input
    id: name
    attributes:
      label: name
      description: whats your name
      placeholder: ex. Rahul
      value: Kishan
    validations:
      required: true
      # default: Kishan123
      # required: true